name: Continuous Deployment

on: [push]

jobs:
  deployUIProject:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './ICWebUI/wwwroot/appsetting.json'
      env:
        APIBaseUrl: ${{ secrets.API_BASE_URL }}
        TEST: ${{ env.TEST }}
            
    - name: Build WebUI project with dotnet
      run: dotnet build ./ICWebUI/ICWebUI.csproj --configuration Release 
    - name: Publish WebUI project using dotnet 
      #create Blazor WebAssembly dist output folder in the project directory
      run: dotnet publish ./ICWebUI/ICWebUI.csproj -c Release --no-build -o publishoutput # Don't build again, just publish
    - name: Publish generated WebUI project to Netlify
      uses: netlify/actions/cli@master #uses Netlify Cli actions
      env: # These are the environment variables added in GitHub Secrets for this repo
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
          args: deploy --dir=publishoutput/wwwroot --prod #push this folder to Netlify
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'